// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pvlbymcgaeaknjlzzbji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2bGJ5bWNnYWVha25qbHp6YmppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2Njc4OTQsImV4cCI6MjA3NTI0Mzg5NH0.n8uuLuAJijqBZhaTVweqzSB35hI9kVx7EFQGfpfKybI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);